<?php include "../_header.php";?>
	<!--
	<section class="g-bg-gray-light-v5 g-py-50">
		<div class="container">
			<div class="d-sm-flex text-center">
				<div class="align-self-center">
					<h2 class="h3 g-font-weight-300 w-100 g-mb-10 g-mb-0--md">Privacy policy</h2>
				</div>
				<div class="align-self-center ml-auto">
					<ul class="u-list-inline">
						<li class="list-inline-item g-color-primary">
							<span>Privacy policy</span>
							<i class="g-color-gray-light-v2 g-ml-5">/</i>
						</li>
						<li class="list-inline-item g-mr-5">
							<a class="u-link-v5 g-color-main g-color-primary--hover" href="#!">Terms and Conditions</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
	-->
	<section class="container g-py-150">
	      <div class="row">
	        <div class="col-lg-6">
	          <div class="d-inline-block g-width-80 g-height-4 g-bg-black mb-3"></div>
	          <h2 class="g-color-black g-font-weight-700 g-font-size-50 g-line-height-1 mb-4">Privacy policy</h2>
			  <p class="h4">Effective date: May 25, 2018</p>
	          <p class="mb-0">This page informs you of our policies regarding the collection, use, and
			disclosure of personal data when you use our Service and the choices you have
			associated with that data.</p>
	        </div>
	      </div>
	    </section>
	
		<section class="g-bg-gray-light-v5">
		      <div class="container g-py-100">
		        <div class="row">
					<div class="col-md-8 offset-md-4">
		            <!-- License -->
		            <div id="license" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
	              		<h2 class="h3 g-color-black mb-3">General</h2>
		              <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>
		              <p>ShareCloth, Inc ("us", "we", or "our") operates the <a href="https://sharecloth.com">https://sharecloth.com</a> (or http://sharecloth.com) website (the "Service").</p>
		              <p>We use your data to provide and improve the Service. By using the Service, you
					agree to the collection and use of information in accordance with this policy.
					Unless otherwise defined in this Privacy Policy, terms used in this Privacy
					Policy have the same meanings as in our Terms and Conditions, accessible from
					<a href="https://sharecloth.com/pages/privacy.php">https://sharecloth.com/pages/privacy.php</a></p>
		            </div>
		            <!-- End License -->

		            <!-- Definitions -->
		            <div id="ownership" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
		              <h3 class="g-color-black mb-3">Definitions</h3>
		              <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>
					  <p class="h5 g-color-black mb-3 g-pt-15">Service</p>
		              <p>Service is the <a href="https://sharecloth.com">https://sharecloth.com</a> website operated by ShareCloth, Inc</p>
		
					  <p class="h5 g-color-black mb-3 g-pt-15">Personal Data</p>
			          <p>Personal Data means data about a living individual who can be identified
					    from those data (or from those and other information either in our
					    possession or likely to come into our possession).</p>
					
					  <p class="h5 g-color-black mb-3 g-pt-15">Usage Data</p>
			          <p>Usage Data is data collected automatically either generated by the use of
				    the Service or from the Service infrastructure itself (for example, the
				    duration of a page visit).</p>

					  <p class="h5 g-color-black mb-3 g-pt-15">Cookies</p>
			          <p>Cookies are small pieces of data stored on your device (computer or mobile
					    device).</p>
					
   					  <p class="h5 g-color-black mb-3 g-pt-15">Data Controller</p>
			          <p>Data Controller means the natural or legal person who (either alone or
				    jointly or in common with other persons) determines the purposes for which
				    and the manner in which any personal information are, or are to be,
				    processed.</p>
					<p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
					
					  <p class="h5 g-color-black mb-3 g-pt-15">Data Processors (or Service Providers)</p>
			          <p>Data Processor (or Service Provider) means any natural or legal person who
				    processes the data on behalf of the Data Controller.

				    We may use the services of various Service Providers in order to process
				    your data more effectively.</p>
					
					  <p class="h5 g-color-black mb-3 g-pt-15">Data Subject (or User)</p>
				      <p>Data Subject is any living individual who is using our Service and is the
					    subject of Personal Data.</p>
				
				
		            </div>
		            <!-- End Ownership -->

		            <!-- Usage -->
		            <div id="collection" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
		              <h3 class="g-color-black mb-3">Information Collection and Use</h3>
		              <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>
		              <p>We collect several different types of information for various purposes to
					provide and improve our Service to you.</p>
						
						<h4 class="g-color-black mb-3 g-pt-15">Types of Data Collected</h4>
						
						<h5 class="g-color-black mb-3 g-pt-15">Personal Data</h5>
						<p>While using our Service, we may ask you to provide us with certain personally
						identifiable information that can be used to contact or identify you
						("Personal Data"). Personally identifiable information may include, but is not
						limited to:</p>
						<ul>
							<li>Email address</li>
							<li>First name and last name</li>
							<li>Phone number</li>
							<li>Address, State, Province, ZIP/Postal code, City</li>
							<li>Cookies and Usage Data</li>
						</ul>
						
						<p>We may use your Personal Data to contact you with newsletters, marketing or
						promotional materials and other information that may be of interest to you.
						You may opt out of receiving any, or all, of these communications from us by
						following the unsubscribe link or instructions provided in any email we send.</p>
						
						<h5 class="g-color-black mb-3 g-pt-15">Usage Data</h5>
						<p>We may also collect information how the Service is accessed and used ("Usage
						Data"). This Usage Data may include information such as your computer's
						Internet Protocol address (e.g. IP address), browser type, browser version,
						the pages of our Service that you visit, the time and date of your visit, the
						time spent on those pages, unique device identifiers and other diagnostic
						data.</p>
						
						<h5 class="g-color-black mb-3 g-pt-15">Tracking &amp; Cookies Data  </h5>
						<p>We use cookies and similar tracking technologies to track the activity on our
						Service and hold certain information.</p>
						<p>Cookies are files with small amount of data which may include an anonymous
						unique identifier. Cookies are sent to your browser from a website and stored
						on your device. Tracking technologies also used are beacons, tags, and scripts
						to collect and track information and to improve and analyze our Service.</p>
						<p>You can instruct your browser to refuse all cookies or to indicate when a
						cookie is being sent. However, if you do not accept cookies, you may not be
						able to use some portions of our Service.</p>
						<p>Examples of Cookies we use:</p>
						<ul>
							<li>Session Cookies. We use Session Cookies to operate our Service.</li>
							<li>Preference Cookies. We use Preference Cookies to remember your preferences
							    and various settings.</li>
							<li>Security Cookies. We use Security Cookies for security purposes.</li>
						</ul>
						
		            </div>
		            <!-- End Usage -->

		            <!-- Use of data -->
		            <div id="usage" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
		              <h3 class="g-color-black mb-3">Use of data</h3>
		              <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>
		              <p>ShareCloth, Inc uses the collected data for various purposes:</p>
		    		  <ul>
						<li>To provide and maintain our Service</li>
						<li>To notify you about changes to our Service</li>
						<li>To allow you to participate in interactive features of our Service when
						    you choose to do so</li>
						<li>To provide customer support</li>
						<li>To gather analysis or valuable information so that we can improve our
						    Service</li>
						<li>To monitor the usage of our Service</li>
						<li>To detect, prevent and address technical issues</li>
						<li>To provide you with news, special offers and general information about
						    other goods, services and events which we offer that are similar to those
						    that you have already purchased or enquired about unless you have opted
						    not to receive such information</li>
					  </ul>
		            </div>
		            <!-- Use of data -->
					
					
					<!-- GDPR -->
					<div id="gdrp" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Legal Basis for Processing Personal Data Under General Data Protection
						Regulation (GDPR)</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>
						<p>If you are from the European Economic Area (EEA), ShareCloth, Inc legal basis
						for collecting and using the personal information described in this Privacy
						Policy depends on the Personal Data we collect and the specific context in
						which we collect it.</p>
						<p>ShareCloth, Inc may process your Personal Data because:</p>
						<ul>
							<li>We need to perform a contract with you</li>
							<li>You have given us permission to do so</li>
							<li>The processing is in our legitimate interests and it's not overridden by
							    your rights</li>
							<li>For payment processing purposes</li>
							<li>To comply with the law</li>
						</ul>
					</div>
					<!-- GDRP -->
					
					<!-- Retention of Data   -->
					<div id="retention" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Retention of Data</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>
						<p>ShareCloth, Inc will retain your Personal Data only for as long as is
						necessary for the purposes set out in this Privacy Policy. We will retain and
						use your Personal Data to the extent necessary to comply with our legal
						obligations (for example, if we are required to retain your data to comply
						with applicable laws), resolve disputes, and enforce our legal agreements and
						policies.</p>
						<p>ShareCloth, Inc will also retain Usage Data for internal analysis purposes.
						Usage Data is generally retained for a shorter period of time, except when
						this data is used to strengthen the security or to improve the functionality
						of our Service, or we are legally obligated to retain this data for longer
						time periods.</p>
					</div>
					<!-- Retention of Data   -->
					
					<!-- Transfer of Data   -->
					<div id="transfer" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Transfer of Data</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>
			
						<p>Your information, including Personal Data, may be transferred to — and
						maintained on — computers located outside of your state, province, country or
						other governmental jurisdiction where the data protection laws may differ than
						those from your jurisdiction.</p>
						<p>If you are located outside United States and choose to provide information to
						us, please note that we transfer the data, including Personal Data, to United
						States and process it there.</p>
						<p>Your consent to this Privacy Policy followed by your submission of such
						information represents your agreement to that transfer.</p>
						<p>ShareCloth, Inc will take all steps reasonably necessary to ensure that your
						data is treated securely and in accordance with this Privacy Policy and no
						transfer of your Personal Data will take place to an organization or a country
						unless there are adequate controls in place including the security of your
						data and other personal information.</p>
					</div>
					<!-- Transfer of Data   -->
					
					<!-- Disclosure of Data   -->
					<div id="disclosure" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Disclosure of Data</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>
						
						<h4 class="g-color-black mb-3">Disclosure for Law Enforcement</h4>
						<p>Under certain circumstances, ShareCloth, Inc may be required to disclose your
						Personal Data if required to do so by law or in response to valid requests by
						public authorities (e.g. a court or a government agency).</p>
						
						<h4 class="g-color-black mb-3">Legal requirements</h4>
						<p>
							ShareCloth, Inc may disclose your Personal Data in the good faith belief that
							such action is necessary to:
						</p>	
					</div>
					<!-- Disclosure of Data   -->
					
					<!-- Security of Data   -->
					<div id="security" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Security of data</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>The security of your data is important to us, but remember that no method of
						transmission over the Internet, or method of electronic storage is 100%
						secure. While we strive to use commercially acceptable means to protect your
						Personal Data, we cannot guarantee its absolute security.</p>

					</div>
					<!-- Security of Data   -->
					
					<!-- DNT signal   -->
					<div id="dnt" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Do Not Track" Signals</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
						</p>
						<p>
							You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
						</p>

					</div>
					<!-- DNT signal  -->
					
					<!-- Data protection rights -->
					<div id="dnt" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>
							If you are a resident of the European Economic Area (EEA), you have certain
							data protection rights. ShareCloth, Inc aims to take reasonable steps to allow
							you to correct, amend, delete, or limit the use of your Personal Data.
						</p>
						<p>
							If you wish to be informed what Personal Data we hold about you and if you
							want it to be removed from our systems, please contact us.
						</p>
						<p>
							In certain circumstances, you have the following data protection rights:
						</p>
						<ul>
							<li class="mb-3">The right to access, update or to delete the information we have on you.
							    Whenever made possible, you can access, update or request deletion of your
							    Personal Data directly within your account settings section. If you are
							    unable to perform these actions yourself, please contact us to assist you.</li>
							<li class="mb-3">The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
							<li class="mb-3">The right to object. You have the right to object to our processing of
							    your Personal Data.</li>
							<li class="mb-3">The right of restriction. You have the right to request that we restrict
								    the processing of your personal information./li>
							<li class="mb-3">
								The right to data portability. You have the right to be provided with a
								    copy of the information we have on you in a structured, machine-readable
								    and commonly used format.
							</li>
							<li class="mb-3">The right to withdraw consent. You also have the right to withdraw your
							    consent at any time where ShareCloth, Inc relied on your consent to
							    process your personal information.
							</li>
						</ul>
						<p><strong>Please note</strong> that we may ask you to verify your identity before responding to
						such requests.</p>
						
						<p>You have the right to complain to a Data Protection Authority about our
						collection and use of your Personal Data. For more information, please contact
						your local data protection authority in the European Economic Area (EEA).</p>
					</div>
					<!-- Data protection rights  -->
					
					<!-- Service providers -->
					<div id="service-providers" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Service providers</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>
							We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
						</p>
						<p>
							These third parties have access to your Personal Data only to perform these
							tasks on our behalf and are obligated not to disclose or use it for any other
							purpose.
						</p>
						
						<h4 class="g-color-black mb-3 g-pt-15">Analytics</h4>
						<p>
							We may use third-party Service Providers to monitor and analyze the use of our
							Service.
						</p>
						
						<h5 class="g-color-black mb-3 g-pt-15">Google Analytics</h5>
						<p>
							Google Analytics is a web analytics service offered by Google that tracks
						    and reports website traffic. Google uses the data collected to track and
						    monitor the use of our Service. This data is shared with other Google
						    services. Google may use the collected data to contextualize and
						    personalize the ads of its own advertising network.
						</p>
						<p>
							You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.
						</p>
						<p>
							For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page:
							    <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a>
						</p>
						
						<h4 class="g-color-black mb-3 g-pt-15">Behavioral Remarketing</h4>
						<p>
							ShareCloth, Inc uses remarketing services to advertise on third party websites
							to you after you visited our Service. We and our third-party vendors use
							cookies to inform, optimize and serve ads based on your past visits to our
							Service.
						</p>
						
						<h5 class="g-color-black mb-3 g-pt-15">Google AdWords</h5>
						<p>Google AdWords remarketing service is provided by Google Inc.</p>
						<p>
							You can opt-out of Google Analytics for Display Advertising and customize
						    the Google Display Network ads by visiting the Google Ads Settings page:
						    <a href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a>
						</p>
						<p>
							Google also recommends installing the Google Analytics Opt-out Browser
						    Add-on <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a> for your web
						    browser. Google Analytics Opt-out Browser Add-on provides visitors with
						    the ability to prevent their data from being collected and used by Google
						    Analytics.
						</p>
						<p>
							For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a>
						</p>
						
						
						<h5 class="g-color-black mb-3 g-pt-20">Twitter</h5>
						<p>
							Twitter remarketing service is provided by Twitter Inc.
						</p>
						<p>
							You can opt-out from Twitter's interest-based ads by following their
							    instructions: <a href="https://support.twitter.com/articles/20170405">https://support.twitter.com/articles/20170405</a>
						</p>
						<p>
							You can learn more about the privacy practices and policies of Twitter by
							    visiting their Privacy Policy page: <a href="https://twitter.com/privacy">https://twitter.com/privacy</a>
						</p>
						
						<h5 class="g-color-black mb-3 g-pt-20">Facebook</h5>
						<p>
							Facebook remarketing service is provided by Facebook Inc.
						</p>
						<p>
							You can learn more about interest-based advertising from Facebook by
							    visiting this page: <a href="https://www.facebook.com/help/164968693837950">https://www.facebook.com/help/164968693837950</a>
						</p>
						<p>
							To opt-out from Facebook's interest-based ads follow these instructions
						    from Facebook: <a href="https://www.facebook.com/help/568137493302217">https://www.facebook.com/help/568137493302217</a>
						</p>
						<p>
							Facebook adheres to the Self-Regulatory Principles for Online Behavioral
						    Advertising established by the Digital Advertising Alliance. You can also
						    opt-out from Facebook and other participating companies through the
						    Digital Advertising Alliance in the USA
						    <a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>, the Digital Advertising Alliance of
						    Canada in Canada <a href="http://youradchoices.ca/">http://youradchoices.ca/</a> or the European Interactive
						    Digital Advertising Alliance in Europe <a href="http://www.youronlinechoices.eu/">http://www.youronlinechoices.eu/</a>,
						    or opt-out using your mobile device settings.
						</p>
						<p>
							For more information on the privacy practices of Facebook, please visit
					    Facebook's Data Policy: <a href="https://www.facebook.com/privacy/explanation">https://www.facebook.com/privacy/explanation</a>
						</p>
					</div>
					<!-- Service providers  -->
					
					<!-- Payments   -->
					<div id="payments" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Payments</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>We may provide paid products and/or services within the Service. In that case,
						we use third-party services for payment processing (e.g. payment processors).
						</p>
						<p>
							We will not store or collect your payment card details. That information is
							provided directly to our third-party payment processors whose use of your
							personal information is governed by their Privacy Policy. These payment
							processors adhere to the standards set by PCI-DSS as managed by the PCI
							Security Standards Council, which is a joint effort of brands like Visa,
							Mastercard, American Express and Discover. PCI-DSS requirements help ensure
							the secure handling of payment information.
						</p>
						<p>
							The payment processors we work with are:
						</p>
						<h4 class="g-color-black mb-3">Stripe</h4>
						<p>
							Their Privacy Policy can be viewed at <a href="https://stripe.com/us/privacy">https://stripe.com/us/privacy</a>
						</p>

					</div>
					<!-- Payments -->
					
					<!-- Marketing-->
					<div id="marketing" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Marketing</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>
							We may use your Personal Data to contact you with newsletters, marketing or
							promotional materials and other information that may be of interest to you.
							To proceed this we use third-party services:
							
						</p>
						
						<h4 class="g-color-black mb-3">MailChimp</h4>	
						<p>
							Their Privacy Policy can be viewed at <a href="https://mailchimp.com/legal/privacy/">https://mailchimp.com/legal/privacy/</a>
						</p>
						
						<h4 class="g-color-black mb-3">HighRise</h4>
						<p>
							Their Privacy Policy can be viewed at <a href="https://highrisehq.com/privacy/">https://highrisehq.com/privacy/</a>
						</p>

					</div>
					<!-- Marketing -->
					
					<!-- Links to Other Sites    -->
					<div id="links" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Links to Other Sites</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>
							Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
						</p>
						<p>
							We have no control over and assume no responsibility for the content, privacy
							policies or practices of any third party sites or services.
						</p>

					</div>
					<!--  Links to Other Sites   -->
					
					<!-- Children's Privacy -->
					<div id="children" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Children's Privacy</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>
							Our Service does not address anyone under the age of 18 ("Children").
						</p>
						<p>
							We do not knowingly collect personally identifiable information from anyone
							under the age of 18. If you are a parent or guardian and you are aware that
							your child has provided us with Personal Data, please contact us. If we become
							aware that we have collected Personal Data from children without verification
							of parental consent, we take steps to remove that information from our
							servers.
						</p>

					</div>
					<!--  Children's Privacy   -->
					
					<!-- Changes to This Privacy Policy    -->
					<div id="changes-to-policy" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Changes to This Privacy Policy</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>
							We may update our Privacy Policy from time to time. We will notify you of any
							changes by posting the new Privacy Policy on this page.
						</p>
						<p>
							We will let you know via email and/or a prominent notice on our Service, prior
							to the change becoming effective and update the "effective date" at the top of
							this Privacy Policy.
						</p>
						<p>
							You are advised to review this Privacy Policy periodically for any changes.
							Changes to this Privacy Policy are effective when they are posted on this
							page.
						</p>

					</div>
					<!-- Changes to This Privacy Policy   -->
					
					<!-- Contact Us  -->
					<div id="changes-to-policy" class="u-shadow-v19 g-bg-white rounded g-pa-40 g-mb-50">
						<h3 class="g-color-black mb-3">Contact Us</h3>
			            <div class="d-inline-block g-width-50 g-height-2 g-bg-black mb-3"></div>

						<p>
							If you have any questions about this Privacy Policy, please contact us:
						</p>
						<ul>
							<li>By email: <strong>hi@sharecloth.com</strong></li>
							<li>By visiting this page on our website: <a href="https://sharecloth.com/contacts.php">https://sharecloth.com/contacts.php</a></li>
						</ul>

					</div>
					<!-- Contact Us  -->				
					
		          </div>
		        </div>
		      </div>
	    </section>
<?php include "../_footer.php";